-- ===========================================================================
-- Unified web analytics for all vanshul.com properties.
-- One anonymous event log + an owner-only aggregate RPC that powers the private
-- /dashboard page. No PII: just a site id, an event kind, a short name
-- (tool id / outbound link / path), an anonymous per-device id, and a timestamp.
--
-- Apply with the Supabase Management API or the SQL editor (project
-- tmngedsmgcgbkbkmsnsw). Safe to re-run (idempotent).
-- ===========================================================================

create table if not exists public.web_events (
  id       bigint generated by default as identity primary key,
  ts       timestamptz not null default now(),
  site     text not null,   -- 'portfolio','tools','cron','json','regex','tokens','links','blog','solaride','adbrain','reader','arcade'
  kind     text not null,   -- 'pageview' | 'tool' | 'link' | 'action'
  name     text,            -- tool id / outbound link / action label
  path     text,            -- location.pathname (+ hash)
  referrer text,            -- referring host (no query strings)
  visitor  text,            -- anonymous per-device id
  user_id  uuid             -- set when signed in (optional)
);

create index if not exists web_events_ts_idx on public.web_events (ts);
create index if not exists web_events_site_kind_idx on public.web_events (site, kind);
create index if not exists web_events_name_idx on public.web_events (kind, name);

-- Bound free-text fields so anonymous inserts can't store oversized rows.
alter table public.web_events drop constraint if exists web_events_bounds;
alter table public.web_events add constraint web_events_bounds
  check (
    char_length(site) <= 32 and
    char_length(kind) <= 16 and
    char_length(coalesce(name, '')) <= 200 and
    char_length(coalesce(path, '')) <= 300 and
    char_length(coalesce(referrer, '')) <= 200 and
    char_length(coalesce(visitor, '')) <= 64
  ) not valid;

alter table public.web_events enable row level security;

-- Anyone may log an event (anonymous). Only known kinds are accepted.
drop policy if exists web_events_insert on public.web_events;
create policy web_events_insert
  on public.web_events for insert
  with check (kind in ('pageview', 'tool', 'link', 'action'));

-- No SELECT policy: the raw event log is never publicly readable. The owner
-- reads aggregates through web_stats() below.

-- ---------------------------------------------------------------------------
-- Owner-only aggregate stats. Times in Asia/Kolkata. `days` bounds the
-- per-day / referrer / breakdown windows (default 30). Also folds in the
-- existing arcade_events log so the dashboard shows games in one place.
-- ---------------------------------------------------------------------------
create or replace function public.web_stats(days int default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v jsonb;
  d int := greatest(1, least(coalesce(days, 30), 365));
  since timestamptz := now() - make_interval(days => d);
begin
  -- `is distinct from` (not `<>`) so an anonymous NULL uid is correctly rejected.
  if auth.uid() is distinct from 'a0c64b9b-7d84-45d4-8ef7-522a6b294b42'::uuid then
    raise exception 'not authorized';
  end if;

  select jsonb_build_object(
    'range_days', d,
    'total_pageviews', (select count(*) from web_events where kind = 'pageview'),
    'total_events',    (select count(*) from web_events),
    'unique_visitors', (select count(distinct visitor) from web_events),
    'pageviews_today', (select count(*) from web_events
                        where kind = 'pageview'
                          and (ts at time zone 'Asia/Kolkata')::date = (now() at time zone 'Asia/Kolkata')::date),
    'events_today',    (select count(*) from web_events
                        where (ts at time zone 'Asia/Kolkata')::date = (now() at time zone 'Asia/Kolkata')::date),

    -- Per-site: pageviews + unique visitors.
    'per_site', (select coalesce(jsonb_agg(jsonb_build_object(
                    'site', site, 'pageviews', pv, 'visitors', uv) order by pv desc), '[]')
                 from (select site,
                              count(*) filter (where kind = 'pageview') pv,
                              count(distinct visitor) uv
                       from web_events group by site) t),

    -- Top tools used, per site.
    'per_tool', (select coalesce(jsonb_agg(jsonb_build_object(
                    'site', site, 'name', name, 'uses', c) order by c desc), '[]')
                 from (select site, name, count(*) c from web_events
                       where kind = 'tool' and name is not null
                       group by site, name order by c desc limit 100) t),

    -- Top outbound links clicked.
    'per_link', (select coalesce(jsonb_agg(jsonb_build_object(
                    'name', name, 'site', site, 'clicks', c) order by c desc), '[]')
                 from (select name, site, count(*) c from web_events
                       where kind = 'link' and name is not null
                       group by name, site order by c desc limit 100) t),

    -- Where visitors come from.
    'top_referrers', (select coalesce(jsonb_agg(jsonb_build_object(
                        'referrer', referrer, 'count', c) order by c desc), '[]')
                      from (select referrer, count(*) c from web_events
                            where referrer is not null and referrer <> ''
                            group by referrer order by c desc limit 25) t),

    -- Hour-of-day distribution of pageviews.
    'by_hour', (select coalesce(jsonb_agg(jsonb_build_object('hour', h, 'pageviews', c) order by h), '[]')
                from (select extract(hour from (ts at time zone 'Asia/Kolkata'))::int h, count(*) c
                      from web_events where kind = 'pageview' group by 1) t),

    -- Rolling daily series over the requested window.
    'by_day', (select coalesce(jsonb_agg(jsonb_build_object(
                  'day', dd, 'pageviews', pv, 'events', ev) order by dd), '[]')
               from (select (ts at time zone 'Asia/Kolkata')::date dd,
                            count(*) filter (where kind = 'pageview') pv,
                            count(*) ev
                     from web_events where ts >= since group by 1) t),

    -- Games (from the existing arcade_events log) in one unified view.
    'arcade', jsonb_build_object(
      'total_visits', (select count(*) from arcade_events where kind = 'visit'),
      'total_plays',  (select count(*) from arcade_events where kind = 'play'),
      'per_game', (select coalesce(jsonb_agg(jsonb_build_object('game', game, 'plays', c) order by c desc), '[]')
                   from (select game, count(*) c from arcade_events
                         where kind = 'play' group by game) t)
    )
  ) into v;
  return v;
end;
$$;

grant execute on function public.web_stats(int) to authenticated;

-- Clean up any diagnostic rows.
delete from public.web_events where site = '__diag__';
